export {default as Navbar} from './Navbar'
export {default as Firstlook} from './Firstlook'
export {default as Courses} from './Courses'
export {default as Browsecat} from './Browsecat'
export {default as Slidingsection} from './Slidingsection'
export {default as Gifsection} from './Gifsection'
export {default as Bluepicsection} from './Bluepicsection'